intfbin/casa-script: various fixes (see detailed message)
First, we try to compute the fully-qualified path of the input script and
always pass that to casapy. We move around in directories a bit and if casapy
can't open the `-c` argument as a file, it treats it as a line of Python,
leading to non-obvious failure modes.

Second, use some "trap" and "kill" magic to do our best to assassinate all of
the CASA subprocess if we get terminated. I think this code is overzealous
right now, and it's certainly not clean, but I'm pretty sure that it will do a
very robust job of making sure that CASA dies if we die.

Third, redirect CASA's input to /dev/null. This matters if the IPython shell
process dies, since by default it wants to read a line of input. This leads to
the script hanging forever in this case. (Yes, this happened.)

Fourth, hook up an environment variable that can cause the work directory to
be preserved, for debugging.

diff --git a/intfbin/casa-script b/intfbin/casa-script
--- a/intfbin/casa-script
+++ b/intfbin/casa-script
@@ -49,20 +49,46 @@
 # environment, so the environment is highly non-vanilla. To exit, just use
 # "exit (1)".
 
+# Set up a fully-qualified path name to the input script so that CASA can
+# always find it, even when we hop around in subdirectories. Otherwise it
+# tries to evaluate the filename as a line of Python.
+
+script=$(cd $(dirname $1) && pwd)/$(basename $1)
+if [ ! -e "$script" ] ; then
+    echo >&2 "error: cannot find input script \"$1\"; should be at \"$script\""
+    exit 1
+fi
+
 workdir=`mktemp -d casascript.XXXXXXXXX`
 cd "$workdir"
 ln -s .. data
 cp /proc/$$/cmdline args
-mkfifo csout ; cat csout &
-mkfifo cserr ; cat cserr >&2 &
-casapy --log2term --nogui -c "$1" >stdout 2>stderr
+mkfifo csout cserr || exit 1
+
+# Process group management insanity:
+# http://stackoverflow.com/a/1645157/3760486 I'm sure I could do a
+# better/cleaner job of this, but I'm pretty sure this code errs on the side
+# of safety, and that's my priority.
+
+trap : SIGTERM SIGINT
+cat csout &
+killpids="-$!"
+cat cserr >&2 &
+killpids="$killpids -$!"
+casapy --log2term --nogui -c "$script" </dev/null >stdout 2>stderr &
+killpids="$killpids -$!"
+wait $!
 retval=$?
+
+if [ $retval -gt 128 ] ; then
+    kill -- $killpids
+fi
 
 if [ $retval -ne 0 ] ; then
     echo >&2 "error: casapy exited with error code $retval; preserving work directory $workdir"
 else
     cd ..
-    rm -rf "$workdir"
+    [ x"$CASASCRIPT_DEBUG_WORK" != x ] || rm -rf "$workdir"
 fi
 
 exit $retval
