hex: abort if no antennas in our assigned instrument
git-svn-id: https://svn.hcro.org/mmm@727 9b194dde-2b4d-0410-98f0-bba1668eb47e

diff --git a/hex/hex-lib-hwsetup b/hex/hex-lib-hwsetup
--- a/hex/hex-lib-hwsetup
+++ b/hex/hex-lib-hwsetup
@@ -35,7 +35,21 @@ set log = $argv[9]
 
 set lo1 = `fxconf.rb hookup $inst1 |grep LO |sed -e 's/.*,\([abcd]\)[1234].*/\1/'`
 set lo2 = `fxconf.rb hookup $inst2 |grep LO |sed -e 's/.*,\([abcd]\)[1234].*/\1/'`
-set alist = `slist.csh $inst1` # assume $inst2 uses same ants
+set alist1 = `slist.csh $inst1`
+set alist2 = `slist.csh $inst2` # unused, assume $alist1 = $alist2 (should take union)
+
+
+# Check setup ...
+
+if ($%alist1 == 0) then
+    echo "$me error: no antennas in instrument $inst1" |& tee -ia $log
+    exit 1
+endif
+
+if ($%alist2 == 0) then
+    echo "$me error: no antennas in instrument $inst2" |& tee -ia $log
+    exit 1
+endif
 
 
 # Do it
@@ -57,24 +71,24 @@ fxlaunch $inst2 |& tee -ia $log
 
 set highfreq = `echo $freq1 $freq2 | awk '{if($1>=$2) print $1; else print $2}'`
 echo "$me setting focus to $highfreq" |& tee -ia $log
-atasetfocus $alist $highfreq
+atasetfocus $alist1 $highfreq
 
-echo "$me setting PAMs to defaults on $alist" |& tee -ia $log
-atasetpams $alist |& tee -ia $log
+echo "$me setting PAMs to defaults on $alist1" |& tee -ia $log
+atasetpams $alist1 |& tee -ia $log
 
 echo "$me setting bandwidths: $bw1 / $bw2" |& tee -ia $log
 bw.csh $inst1 $bw1 |& tee -ia $log
 bw.csh $inst2 $bw2 |& tee -ia $log
 
 echo "$me waiting for focus completion" |& tee -ia $log
-waitfocus $alist $highfreq
-atagetfocus $alist >$pfx-focus.txt
+waitfocus $alist1 $highfreq
+atagetfocus $alist1 >$pfx-focus.txt
 
 echo "$me pointing to North Pole for autoattening ..." |& tee -ia $log
-atasetazel -w $alist 0 41 |& tee -ia $log
+atasetazel -w $alist1 0 41 |& tee -ia $log
 
 echo "$me LNAs on" |& tee -ia $log
-atalnaon $alist |& tee -ia $log
+atalnaon $alist1 |& tee -ia $log
 
 echo "$me setting integration times to $inttime ..." |& tee -ia $log
 (setintfx.csh $inttime $inst1 |& tee -ia $log) &
diff --git a/hex/hex-obs-loop b/hex/hex-obs-loop
--- a/hex/hex-obs-loop
+++ b/hex/hex-obs-loop
@@ -105,12 +105,23 @@ end
 
 set lo1 = `fxconf.rb hookup $inst1 |grep LO |sed -e 's/.*,\([abcd]\)[1234].*/\1/'`
 set lo2 = `fxconf.rb hookup $inst2 |grep LO |sed -e 's/.*,\([abcd]\)[1234].*/\1/'`
-set alist = `slist.csh $inst1` # assume $inst2 uses same ants
+set alist1 = `slist.csh $inst1`
+set alist2 = `slist.csh $inst2` # unused, assume $alist1 = $alist2 (should take union)
 
 set begin = `date +"%H %M" | awk '{print $1 + ($2 / 60) - 0.1}'`
 
 
 # Setup
+
+if ($%alist1 == 0) then
+    echo "$me error: no antennas in instrument $inst1" |& tee -ia $log
+    exit 1
+endif
+
+if ($%alist2 == 0) then
+    echo "$me error: no antennas in instrument $inst2" |& tee -ia $log
+    exit 1
+endif
 
 onintr fail
 
@@ -174,7 +185,7 @@ while (1)
 
     set highfreq = `echo $freq1 $freq2 | awk '{if($1>=$2) print $1; else print $2}'`
     echo "$me `date`- setting focus to $highfreq" |& tee -ia $log
-    atasetfocus $alist $highfreq
+    atasetfocus $alist1 $highfreq
 
     echo "$me setting sky freqs: $lo1 $freq1 / $lo2 $freq2" |& tee -ia $log
     ataunlockserver lo$lo1 $pfx |& tee -ia $log
@@ -197,9 +208,9 @@ while (1)
     endif
 
     echo "$me waiting for focus completion" |& tee -ia $log
-    waitfocus $alist $highfreq
+    waitfocus $alist1 $highfreq
     echo "$me focus setup at `date`" >>$subpfx-focus.txt
-    atagetfocus $alist >>$subpfx-focus.txt
+    atagetfocus $alist1 >>$subpfx-focus.txt
 
     # Check time left again
 
diff --git a/hex/hex-obs-nosetup b/hex/hex-obs-nosetup
--- a/hex/hex-obs-nosetup
+++ b/hex/hex-obs-nosetup
@@ -143,8 +143,19 @@ echo "$me args $flt" |& tee -ia $log
 
 set switch="`cat /home/obs/bin/genswitch`"
 # we drive only the ants in $inst1 -- it is assumed that $inst2 contains
-# the same antennas.
-set alist = `slist.csh $inst1`
+# the same antennas. We should take their union.
+set alist1 = `slist.csh $inst1`
+set alist2 = `slist.csh $inst2`
+
+if ($%alist1 == 0) then
+    echo "$me error: no antennas in instrument $inst1" |& tee -ia $log
+    exit 1
+endif
+
+if ($%alist2 == 0) then
+    echo "$me error: no antennas in instrument $inst2" |& tee -ia $log
+    exit 1
+endif
 
 spolist.csh $inst1 # makes list of antpols in file 'antpols'
 set antpols1 = `cat antpols`
@@ -276,10 +287,10 @@ foreach pnt (`seq 1 $npnt`)
     frot.csh $inst1 $ephem $freq1 `pwd` start
     frot.csh $inst2 $ephem $freq2 `pwd` start
 
-    echo "$me pointing $alist" |& tee -ia $log
-    echo "-- atatrackephem $alist $ephem -w" |& tee -ia $outpfx-track.log
+    echo "$me pointing $alist1" |& tee -ia $log
+    echo "-- atatrackephem $alist1 $ephem -w" |& tee -ia $outpfx-track.log
     echo "--   at: `date`" |& tee -ia $outpfx-track.log
-    atatrackephem $alist $ephem -w |& tee -ia $outpfx-track.log
+    atatrackephem $alist1 $ephem -w |& tee -ia $outpfx-track.log
 
     # Run the catchers!
     echo "$me launching catchers at `date`" |& tee -ia $log
