hex: create summary files for each scan to aid in picking out linked data
git-svn-id: https://svn.hcro.org/mmm@703 9b194dde-2b4d-0410-98f0-bba1668eb47e

diff --git a/hex/hex-obs-nosetup b/hex/hex-obs-nosetup
--- a/hex/hex-obs-nosetup
+++ b/hex/hex-obs-nosetup
@@ -57,6 +57,16 @@
 #    n'th pointing on the first instrument
 # $outpfx-p$n-$freq2$c2 - Miriad data file for the observations of the
 #    n'th pointing on the second instrument
+# $outpfx-summ-$time$c1.hexsumm - "hex summary" file listing the data
+#    files corresponding to this observing run on the first instrument. 
+#    $time is the current local time formatted as HH:MM:SS; it is used 
+#    to prevent filename clashes between multiple hex summary files if
+#    more than one observation with the same setup is run in a single
+#    directory.
+# $outpfx-summ-$time$c2.hexsumm - Analogous to the above. The value of
+#    $time is not guaranteed to be identical to that of the previous
+#    file, but in practice it almost always will be. You shouldn't
+#    ever find yourself relying on that fact, though.
 #
 # Several standard miscellanous logfiles are created by scripts invoked
 # by this program as well:
@@ -197,6 +207,29 @@ set bw2 = `ibob i1.$fx2 regread bwsel |cut -c9`
 set bw2 = $bws[$bw2]
 
 
+# Set up for logging this session to the summary files
+# that tell the automated tools about this particular session
+
+set n = 0
+
+while (1)
+    set summfile1 = $outpfx-summ-`date +%H:%M:%S`$ic1.hexsumm
+    set summfile2 = $outpfx-summ-`date +%H:%M:%S`$ic2.hexsumm
+    if (! -f $summfile1 && ! -f $summfile2) break
+    if ($n > 9) then
+	echo "$me: fatal error: can't come up with new summary file names?!"
+	exit 1
+    endif
+    sleep 1
+    @ n = $n + 1
+end
+
+echo tstart `date -u +%y%b%d:%H:%M:%S.0` >$summfile1
+echo nfull $npnt >>$summfile1
+echo tstart `date -u +%y%b%d:%H:%M:%S.0` >$summfile2
+echo nfull $npnt >>$summfile2
+
+
 # Run the observations
 
 echo "$me inst1 $inst1 freq $freq1 bw $bw1" |& tee -ia $log
@@ -267,13 +300,29 @@ foreach pnt (`seq 1 $npnt`)
     if ($pnt == 1) then
 	echo "compass `pwd`/$vpf2 $tstart $tend $inst2" > ~/karto/compass.log
     endif
+
+    # Note these observations in the summary files
+    echo scan `printf %02d $pnt0` $vpf1 >>$summfile1
+    echo scan `printf %02d $pnt0` $vpf2 >>$summfile2
 end
+
+# Close out the summary files -- lack of a 'success' entry
+# implies that observing crashed or aborted 
+echo tend `date -u +%y%b%d:%H:%M:%S.0` >>$summfile1
+echo success 1 >>$summfile1
+echo tend `date -u +%y%b%d:%H:%M:%S.0` >>$summfile2
+echo success 1 >>$summfile2
 
 echo "$me ended successfully at `date`" |& tee -ia $log
 exit 0
 
 fail:
 echo "$me aborting" |& tee -ia $log
+
+# Try to close out the summary files -- may be helpful
+# for recovering if most of the observation is still usable
+echo tend `date -u +%y%b%d:%H:%M:%S.0` >>$summfile1
+echo tend `date -u +%y%b%d:%H:%M:%S.0` >>$summfile2
 
 # Kill rotators just in case
 frot.csh $inst1 $ephem $freq1 `pwd` kill
diff --git a/hex/hex-proc-create b/hex/hex-proc-create
--- a/hex/hex-proc-create
+++ b/hex/hex-proc-create
@@ -2,7 +2,9 @@
 #
 # Create a new analysis directory for processing hex-style observations.
 # The only work done here is to "shadow" the data into the analysis
-# directory. The next step is to flag and calibrate the data with 
+# directory and flag out data outside of the observations' time range
+# (in case the dataset is appended to multiple times during a loop
+# observations). The next step is to flag and calibrate the data with 
 # hex-proc-prep.
 
 # Uncomment to debug the commands executed by this script
@@ -12,8 +14,8 @@
 source `dirname $0`/hex-lib-checkenv
 
 if ($#argv < 2) then
-    echo "Usage: [vis1] [vis2 ...]     [analysis dir]"
-    echo "E.g.:  hex-3c48-hp7-p*-1430a work"
+    echo "Usage: [summary file] [analysis dir]"
+    echo "E.g.:  hex-3c48-hp7-summ-23:59:59a.hexsumm 3c48-1430"
     exit 1
 endif
 
@@ -30,6 +32,55 @@ if (-e $workdir/data-rawdata.txt) then
 endif
 
 
+# Figure out whether we've been passed a summary file or (easter egg!)
+# a list of UV datasets
+
+if (-f $1 && $#argv == 2) then
+    # Summary file.
+    set summdir = `dirname "$1"`
+    set tstart = `grep tstart "$1" |cut -d' ' -f2`
+    set tend = `grep tend "$1" |cut -d' ' -f2`
+    set nfull = `grep nfull "$1" |cut -d' ' -f2`
+
+    grep success "$1" >& /dev/null
+    if ($status) then
+	echo "Warning: no success indicator in summary file."
+	echo "  This observation may have failed or been aborted."
+    endif
+
+    # make sure to get them in proper order
+    set relvises = (`grep scan "$1" |sort |cut -d' ' -f3`)
+    set nvis = $#relvises
+
+    if ($nfull != $nvis) then
+	echo "Warning: this hex run didn't include all of the scans that "
+	echo "  it should have. There may not be enough data to analyze."
+    endif
+
+    # Convert to absolute paths
+    set vises = ()
+
+    foreach rvis ($relvises)
+	set vises = ($vises $summdir/$rvis)
+    end
+else
+    set tstart = none
+
+    # List of UV datasets.
+    @ nvis = $#argv - 1
+    set vises = (${argv[1-$nvis]})
+
+    # Check that that's actually what they are
+    foreach vis ($vises)
+	if (! -e $vis/visdata) then
+	    echo "Error: arguments appear to include list of UV datasets, but"
+	    echo "  no such file $vis/visdata"
+	    exit 1
+	endif
+    end
+endif
+
+
 # Shadow the raw datasets into the work directory
 #
 # FIXME: this is where we should do sanity-checking on the input data:
@@ -39,8 +90,6 @@ endif
 
 set old = `pwd`
 @ n = 0
-@ nvis = $#argv - 1
-set vises = (${argv[1-$nvis]})
 
 foreach vis ($vises)
     set vis = `cd $vis ; pwd`
@@ -69,5 +118,16 @@ foreach vis ($vises)
     @ n = $n + 1
     cd $old
 end
+
+
+# If a time range is specified, flag out data outside of the relevant
+# time period.
+
+if ($tstart != none) then
+    foreach vis ($workdir/vis??)
+	echo uvflag flagval=f select="-time($tstart,$tend)" vis=$vis
+	uvflag flagval=f select="-time($tstart,$tend)" vis=$vis
+    end
+endif
 
 exit 0
